### ISSUE TITLE
Clear way to tell what day messages were sent on

### ISSUE THREAD

**Issue by towerofnix** [towerofnix/bantisocial#15]
Discord makes splits like this:

![Discord splits](https://user-images.githubusercontent.com/9948030/33525874-73c7d418-d82f-11e7-92f8-1af74ebb970b.png)

I like this.

Riot does similar:

![Riot "today" heading](https://user-images.githubusercontent.com/9948030/33525889-9bd669ba-d82f-11e7-8a50-c0daae72f1fc.png)

..but I prefer Discord's style.

**Comment by heyitsmeuralex** [comment]
Or...

We could just append the date/equivalent to messages old enough to require it. e.g.
![image](https://user-images.githubusercontent.com/9429556/33564321-297506ae-d912-11e7-98f9-3c4e16594ef4.png)

**Comment by PullJosh** [comment]
That is definitely better. We should also allow hovering over the date to see the exact date and time in UTC.

**Comment by heyitsmeuralex** [comment]
>UTC

why

**Comment by heyitsmeuralex** [comment]
Been completed on the `riot` branch. See #77.
