### ISSUE TITLE
Don't repeat message author

### ISSUE THREAD

**Issue by heyitsmeuralex** [towerofnix/bantisocial#16]
Bad:
![image](https://user-images.githubusercontent.com/9429556/33525898-da7185ba-d82f-11e7-9aab-683518e84d83.png)

Be like every other chat application and don't repeat people's names if they send consecutive messages, thanks 🎉

**Comment by towerofnix** [comment]
Note that, on scrollback (see #31), if new (old :) ) messages are added immediately before a pre-existing message from the same user, the username header should "move up" to the top newly-added message.

That could mean doing `headerEl.remove(); topNewMessageEl.appendChild(headerEl)`, but maybe it could be as simple as making "message group" elements?

```html
<div class="message-group">
  <div class="message-group-author">alex</div>
  <div class="messages">
    <div class="message">1</div>
    <div class="message">2</div>
    <div class="message">3</div>
  </div>
</div>
```

Then messages from scrollback could be inserted at the top:

```html
<div class="message-group">
  <div class="message-group-author">alex</div>
  <div class="messages">
    <!-- Insert these: -->
    <div class="message">-1</div>
    <div class="message">0</div>

    <div class="message">1</div>
    <div class="message">2</div>
    <div class="message">3</div>
  </div>
</div>
```
