### ISSUE TITLE
Allow linking to different servers in messages

### ISSUE THREAD

**Issue by PullJosh** [towerofnix/bantisocial#20]
There is already a feature in place to allow linking to a channel from within the same server using # syntax (`#general`).

The idea here is to also allow linking to channels *from other servers*.

## Proposed Syntax
**Link to server only:** `+` followed by server ~~name~~ URL
Examples: `+nonfree.com`, `+AT-fun.com`, etc  

**Link to server and channel:** server link + channel link combined
Examples: `+nonfree.com#newsroom`, `+AT-fun.com#general`, etc

**Comment by heyitsmeuralex** [comment]
>server name

Server _url_, you mean. We're going decentralised here!

**Comment by heyitsmeuralex** [comment]
Can't do this until connections to multiple servers (on the client) is implemented. We'll need a seperate issue for that.
