### ISSUE TITLE
Separate client from its host server

### ISSUE THREAD

**Issue by heyitsmeuralex** [towerofnix/bantisocial#25]
The client should be able to connect to multiple servers at once. Decenteralized = good! See: [riot.im](https://riot.im/)

Needs UI @PullJosh and also big implementation, separating SessionActors per-server, etc.

Blocks #20.

**Comment by PullJosh** [comment]
Currently working on some slight redesign work. Would it be useful to add non-functioning UI for this in preparation for the backend updates?

**Comment by towerofnix** [comment]
@PullJosh Actually, I'm not sure there would *be* any backend updates, besides making the program which hosts the `site` folder be separate - I think the only needed change would be in the client, making the socket connect to a different host. That said, @heyitsmeuralex would know how to actually do that better than me - this will mean managing multiple sockets at once.

But all that's irrelevant to what you need to know, which I think is, yes, making a non-functioning UI would be helpful! :package:

**Comment by PullJosh** [comment]
Sweet. Got to go for now, but I'll be back later today with fun design updates.

**Comment by towerofnix** [comment]
Blocked by #41.

**Comment by towerofnix** [comment]
Fixed by #45.
