### ISSUE TITLE
Make HTML valid

### ISSUE THREAD

**Issue by towerofnix** [towerofnix/bantisocial#30]
Particularly, add `<html>`/`<body>`/etc elements, and stick to using double quotes for attributes (`<a href="blah">`).

Assigning @PullJosh since you're working on the HTML code right now, but everyone who works on it should keep this in mind!

**Comment by heyitsmeuralex** [comment]
\>:(

**Comment by heyitsmeuralex** [comment]
Gonna label this as `wontfix` because of #77 and how that really isn't very standard.
