### ISSUE TITLE
Channel names in messages should be clickable

### ISSUE THREAD

**Issue by towerofnix** [towerofnix/bantisocial#4]
In Discord format, i.e. `#channel-name`.

Should make the user automatically jump to that channel.

@heyitsmeuralex hey-ho? I didn't write the message formatter code :)

This probably won't be reasonably useful until channel names are forced to be whitespace-less.. unless you want to try to implement `#(channel name)`, eh? :)

**Comment by heyitsmeuralex** [comment]
> unless you want to try to implement #(channel name), eh?

no
channel names and usernames should have no whitespace
