### ISSUE TITLE
Use history.pushState

### ISSUE THREAD

**Issue by heyitsmeuralex** [towerofnix/bantisocial#54]
It would be nice for the back/forward buttons on the browser to actually go forwards/backwards in whatever you've been doing on the client.

e.g. If I click a link `+topcake.ws`, hitting _the browser's back button_ should send me back to the server and channel I came from.

This is going to need some kind of internal history storage.

**Comment by towerofnix** [comment]
>This is going to need some kind of internal history storage.

Will it? Couldn't it just detect the hash changing, and apply changes based on that?

**Comment by heyitsmeuralex** [comment]
Well, the hash doesn't actually change in the browser. It probably should, but what happens when you're connected to a remote server?

The history storage also seems more stable -- a general user can edit the hashname and break stuff.

**Comment by heyitsmeuralex** [comment]
Fixed in the riot branch. Uses `location.hash` anyway, because it'd be nice for the client to work entirely statically (i.e. github pages).
