### ISSUE TITLE
User list API endpoint

### ISSUE THREAD

**Issue by heyitsmeuralex** [towerofnix/bantisocial#55]
Plus online/offline state, based on whether the client has pinged recently or not. Would be helpful to include this at `/api/user/:userID` too.

**Comment by towerofnix** [comment]
A user should be able to decide whether they want to appear as invisible or not (i.e. always offline), and that option should not be returned on `/user/:userID`, since asking whether someone's hiding themself just seems kind of rude. It's not strictly necessary to begin work on this, though.

**Comment by heyitsmeuralex** [comment]
> asking whether someone's hiding themself seems kind of rude

Surely it'd just return `{ online: false }` if they're actually-online-but-invisible?

**Comment by towerofnix** [comment]
Yup. I'm just talking about `/user/:userID`, which contains database data about the user; that shouldn't include an `isInvisible` field.
