### ISSUE TITLE
Make the client actually look good

### ISSUE THREAD

**Issue by heyitsmeuralex** [towerofnix/bantisocial#7]

**Comment by heyitsmeuralex** [comment]
@PullJosh you offered to help out with this?

**Comment by PullJosh** [comment]
I'd be up for it!

**Comment by PullJosh** [comment]
You're welcome.

**Comment by towerofnix** [comment]
Sorry..! @heyitsmeuralex :thinking:

Having two sets of designer-eyes is handy, though! If you could look at the style now and see what could be better (and/or you have ideas for the chat system in general, of course), that would still be helpful.

**Comment by heyitsmeuralex** [comment]
It could do with some animations and other general polish if I'm honest. Go for it @PullJosh 😜

**Comment by PullJosh** [comment]
Don't you worry. I'll be tearing alex's design to shreds.
