### ISSUE TITLE
Mark code blocks as white-space: pre

### ISSUE THREAD

**Issue by towerofnix** [towerofnix/bantisocial#71]
At the moment, they aren't, which makes this..

```
for (let i = 0; i < 100; i++) {
  alert(
    'haha pranked' + i
  )
}
```

..display as this:

```
for (let i = 0; i < 100; i++) {
alert(
'haha pranked' + i
)
}
```

**Comment by towerofnix** [comment]
@heyitsmeuralex - this isn't as simple as it should be because the formatter code apparently makes a bunch of separate `<code>` blocks:

![this image is named spancode which reminds me of github.com/towerofnix/spancode](https://user-images.githubusercontent.com/9948030/33807365-96d859de-ddcd-11e7-8c42-0b5183c08c89.png)

**Comment by heyitsmeuralex** [comment]
huh whoops
