### ISSUE TITLE
Drop "revisions" feature + discussion on message deletion?

### ISSUE THREAD

**Issue by towerofnix** [towerofnix/bantisocial#73]
Ping @heyitsmeuralex for discussion.

Originally I had it so that old versions of messages could be accessed, so that if somebody says something that's Bad, that's tracked. But we'll be implementing message deleting - if anybody can delete their own messages, then there's not much reason to keep track of old versions. (And I'm leaning towards letting people delete their own messages, rather than, say, limiting the action to admins; that way people have (at least a little) control over what happens with what they've said. I'd rather trust someone to undo something stupid they just sent so nobody needs to see it than force everything that everyone's said to permanently be in the open, transparent space.)

**Comment by PullJosh** [comment]
I like that. I would still *label* posts that have been edited, but don't keep old versions.

**Comment by towerofnix** [comment]
Sounds good to me - I'll remove this from the backend. @heyitsmeuralex as you're writing/rewriting the client (per #74) don't bother with re-implementing "view old revisions". (Obviously you'll still need to make edited messages update automatically, though!)
