### ISSUE TITLE
Should we use React/Vue/Marko/etc?

### ISSUE THREAD

**Issue by PullJosh** [towerofnix/bantisocial#74]
As the codebase grows larger -- particularly the parts which pertain to accessing the API and generating HTML based on the response -- things are quickly growing complicated. Fortunately, this is mostly a solved problem. Frameworks like React exist to solve just an issue such as this: generating DOM elements from data being received.

The question: Are we willing to join the dark side?

**Pros:**
- Easily generate all the markup for... well... everything. From messages to online indicators to channel lists, everything can be generated quickly and cleanly.
- Less likely for bizarre bugs to emerge when handling large amounts of data
- Keep spaghetti to a minimum
- Be hipster developers

**Cons:**
- Need to compile JS(?)
- Need to load large framework file (can be mitigated by using CDN with caching)
- No longer entitled to label everything that uses a framework "webshit"

**Comment by PullJosh** [comment]
Personally, I'm in favo(u)r of using a framework, but I'm not really the one dealing heavily with JS, so take my opinion with a grain of salt.

**Comment by heyitsmeuralex** [comment]
I'm all for it and I'm Mr. Client-side :taco:

That said, **which**?

* **React** is a meme and also meh :-1:
* **Vue** I used a while ago and wasn't too impressed, but apparently it's better now
* **Marko** is awesome
* **Riot** is awesome & lightweight :+1:

**Comment by heyitsmeuralex** [comment]
Also note that implementing [PullJosh's redesign](https://codepen.io/PullJosh/pen/OOYZWK) requires a decently large rewrite anyway, so this would be a good time to try out a framework.

**Comment by towerofnix** [comment]
>I'm all for it and I'm Mr. Client-side :taco:

This is a really good argument honestly. As a fellow human being, I'm resistant to change, but in this case *I* don't actually have to deal with the change. That's motivating! :shipit:

>Riot is awesome & lightweight :+1:

Riot is probably slow because it sounds like Riot, which is slow, but who knows? You say it's good! :tada:

Reading through their homepage makes it sound good. I'm definitely interested to see what it would look like when rewriting it; probably good.

**Comment by heyitsmeuralex** [comment]
I'll check out Riot then - can we have another issue for the actual implementation of this + the UI redesign?

**Comment by towerofnix** [comment]
Yes, we can.

Iff you make it. :package: :shipit:

**Comment by heyitsmeuralex** [comment]
>Iff you make it. 📦 :shipit:

**Angery!** I'm busy installing things 😜
