### ISSUE TITLE
Rewrite client with Riot.js

### ISSUE THREAD

**Issue by towerofnix** [towerofnix/bantisocial#77]
..all the while implementing @PullJosh's design.

(This issue is mainly here so we can label virtually all "client" issues as blocked.)

PS I can and will label everything as webscale! :trollface:

**Comment by heyitsmeuralex** [comment]
See #74 for previous discussion on this.

**Comment by towerofnix** [comment]
@heyitsmeuralex When are you making a PR, eh? :)

**Comment by heyitsmeuralex** [comment]
>eh

How canadian

**Comment by towerofnix** [comment]
@heyitsmeuralex note: the client does not need to be completed before it's merged; only to a usable point (sending messages should work, as well as switching between channels, and registering/logging in).

We need it to be merged before *anyone* can put any further work into client implementations. Make a PR when you have a chance? No pressure-- little bit of pressure. :smiley_cat:

(That said, I totally get you've not been feeling 110% lately and been fairly busy, and I really don't want to make you feel obligated or forced to work on this. Just when you have a chance that also works for you! Riot branch seems to have good progress on it so I'd rather this just be a friendly nudge to check if maybe it's ready for a PR :package:)

**Comment by heyitsmeuralex** [comment]
>I really don't want to make you feel obligated or forced to work on this.

I finish school tomorrow at lunchtime. No worries :shipit:

> edit

xd

I see where you're coming from on the PR front - I'll quickly finish some stuff up now.

All it really needs is sending messages and we're ~~gucci~~ good to PR.
