### ISSUE TITLE
Weechat script

### ISSUE THREAD

**Issue by TheInitializer** [towerofnix/bantisocial#79]
Is the API in a state where I can start on this?

**Comment by towerofnix** [comment]
Almost certainly "yes".

There's going to be a big client rewrite soon/now, but that shouldn't have too much impact on the backend. *If any changes to existing APIs are made* (and there probably won't be), it probably wouldn't be much for you/other client writers to implement.

**Comment by heyitsmeuralex** [comment]
Go for it 🎉
