### ISSUE TITLE
Implement fetch recent messages in channel API endpoint

### ISSUE THREAD

**Issue by heyitsmeuralex** [towerofnix/bantisocial#8]
Needed - when you change channel at the moment there is no way to view the backlog of messages, leaving you with zero context or infomation about what's inside the channel.

**Comment by towerofnix** [comment]
In order to do this I'll need to change message dates to be stored as `Date.now()` and not ISO timestamps (for easier querying). @heyitsmeuralex, you'll probably need to update the code in your PR which displays message timestamps.
