### ISSUE TITLE
Document the API

### ISSUE THREAD

**Issue by heyitsmeuralex** [towerofnix/bantisocial#80]
API docs in the form of a Github Wiki would be v. nice 🌮

**Comment by towerofnix** [comment]
Wiki is open!

**Comment by towerofnix** [comment]
WIP API page [here](https://gist.github.com/towerofnix/a139521ca3bea40693fb133f3a85fe87). (That document assumes that #81 is completed.)

**Comment by towerofnix** [comment]
Completed: https://github.com/towerofnix/bantisocial/wiki/API

:tada:
